// Generates src/styles/fluid.css: NextUp's fluid type and space scale (Utopia, utopia.fyi).
// One scale for every page, so sizes are decided here once instead of per page (docs/RESPONSIVE.md).
//
//   node scripts/fluid-tokens.mjs          # rewrite src/styles/fluid.css
//   node scripts/fluid-tokens.mjs --check  # exit 1 when the file is out of date (npm test runs this check too)
//
// Every token is a clamp(): it grows in a straight line from a 360px phone to a 1920px monitor and
// stops at both ends, so there is no jump at a breakpoint. Type is a hand-picked UI ramp, not a
// modular ratio: the app leans on 12px meta next to 13px secondary text, which a ratio would merge.
// The steps stay apart at every width (tests/unit/fluid.test.ts checks it), so labels, body, ledes
// and titles can never land on the same size the way a scaled design with a 12px floor did.
import { calculateClamp, calculateSpaceScale, checkWCAG } from "utopia-core";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const MIN_W = 360, MAX_W = 1920;

// [name, px at 360, px at 1920, what it is for]
export const TYPE = [
  ["xs", 12, 12, "meta, tags, badges, timestamps - the floor (nothing is smaller)"],
  ["sm", 12.5, 13.5, "labels, secondary lines, captions, small buttons"],
  ["md", 14, 15, "body text, buttons, inputs on laptops, list titles"],
  ["lg", 15.5, 17, "ledes, card headings, the opened item's intro"],
  ["xl", 18, 21, "section headings, big numbers"],
  ["2xl", 21, 26, "page headings, list card titles"],
  ["3xl", 24, 32, "the opened case's title"],
  ["4xl", 28, 40, "display: sign-in and empty pages"],
];

// Space: Utopia's scale on a 16px -> 18px base. The single sizes barely move; the pairs ("xs-s",
// "s-m") are the fluid ones - use them for gaps between cards and padding inside them.
const SPACE = { minSize: 16, maxSize: 18, negativeSteps: [0.75, 0.5, 0.25], positiveSteps: [1.5, 2, 3], customSizes: ["s-l", "xs-m"] };

const rem = (px) => +(px / 16).toFixed(4) + "rem";
const lines = [];
lines.push("/* GENERATED by scripts/fluid-tokens.mjs - edit the scale there, then run it. Do not edit by hand.");
lines.push(`   Fluid type and space (Utopia): each token grows from a ${MIN_W}px phone to a ${MAX_W}px monitor and stops`);
lines.push("   at both ends. Font sizes in CSS use only these (npm run lint enforces it; docs/RESPONSIVE.md). */");
lines.push(":root {");
for (const [name, min, max, use] of TYPE) {
  const value = min === max ? rem(min) : calculateClamp({ minWidth: MIN_W, maxWidth: MAX_W, minSize: min, maxSize: max, relativeTo: "viewport-width" });
  const wcag = checkWCAG({ min, max, minWidth: MIN_W, maxWidth: MAX_W });
  if (wcag?.length) throw new Error(`--nh-fs-${name} fails WCAG 1.4.4 (200% zoom) between ${wcag[0]}px and ${wcag[1]}px`);
  lines.push(`  --nh-fs-${name}: ${value}; /* ${min}${min === max ? "" : "-" + max}px: ${use} */`);
}
// Not a step: text fields on phones stay at 16px, or iOS zooms the page in on focus (docs/RESPONSIVE.md rule 6).
lines.push("  --nh-fs-input: 1rem; /* 16px: text fields on phones - smaller makes iOS zoom in on focus */");
const space = calculateSpaceScale({ minWidth: MIN_W, maxWidth: MAX_W, ...SPACE, relativeTo: "viewport-width" });
for (const s of [...space.sizes, ...space.oneUpPairs, ...space.customPairs]) {
  lines.push(`  --nh-sp-${s.label}: ${s.clamp}; /* ${s.minSize}-${s.maxSize}px */`);
}
lines.push("}");
const css = lines.join("\n") + "\n";

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "styles", "fluid.css");
if (process.argv.includes("--check")) {
  let now = "";
  try { now = readFileSync(out, "utf8").replace(/\r\n/g, "\n"); } catch { /* missing counts as stale */ }
  if (now !== css) { console.error("src/styles/fluid.css is out of date: run node scripts/fluid-tokens.mjs"); process.exit(1); }
} else {
  writeFileSync(out, css);
  console.log("wrote " + out);
}
